version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "service cron start &&
             python manage.py crontab add &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_tour_pack:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5435"
    command: -p 5435
    env_file:
      - .env

volumes:
  postgres_data_tour_pack:
