version: '3.9'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.prod
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - static_volume:/app/staticfiles  # Add this line
      - media_volume:/app/media         # Add this line
    environment:
      - DOMAIN=${DOMAIN}

    depends_on:
      - web

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  static_volume:
  media_volume: