version: '3.9'

services:
  web2:
    build:
        context: .
        dockerfile: Dockerfile.prod
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8080
    expose:
      - 8080
    volumes:
      # - static_volume:/code/static
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env.prod
    depends_on:
      - db2


  db2:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db


  caddy3:
    image: caddy:2
    ports:
      - "8081:80"  # Changed HTTP port to 8081 as requested
      - "9443:443" # HTTPS port remains 9443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web2

volumes:

  postgres_data:
  Caddyfile:
  caddy_data:
  caddy_config:
  static_volume:
  media_volume:

