version: '3'

services:
  web:
    image: my_django_app:prod # Your built image
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    env_file:
      - .env.prod
    volumes:
      - ./static:/code/static  # Optional, adjust based on your setup
    depends_on:
      - db  # If you are using a database service
    networks:
      - app_network

  db:
    image: postgres:14-alpine  # Example database service (optional)
    env_file:
      - .env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
